## Hotel Booking Demand

### Business Problem Understanding

**Context**

Perusahaan yang bergerak di bidang perhotelan ingin melihat adanya pengelolaan reservasi pemesanan kamar. Terdapat berbagai orang yang telah melakukan pemesanan hotel dengan berbagai pilihan tipe kamar. Perusahaan ingin memprediksi adanya pengaruh dari pembatalan dari pemesanan.

Target :

0 : Pembatalan Pemesanan

1 : Tidak Membatalkan Pemesanan

### Attribute Information

| Attribute | Data Type, Length | Description |
| --- | --- | --- |
|Country| Text |Suatu organisasi yang ada di wilayah tertentu baik secara geografis, politik, dan sosial yang berdaulat|
|Market_segment| Text |Kategori pelanggan yang menjadi target atau sumber dari pemesanan kamar hotel.|
|Previous_cancellations	| Long |Jumlah pembatalan sebelumnya oleh pelanggan tertentu |
|Booking_changes| Long |Jumlah dari perubahan dalam permintaan pemesanan oleh pelanggan |
|Deposit_type| Text |Tipe deposit yang dipilih oleh pelanggan ketika melakukan pemesanan hotel|
|Days_in_waiting_list| Long | Jumlah dari hari pemesanan yang berada didalam daftar tunggu sebelum akhirnya dikonfirmasi atau dibatalkan|
|Customer_type| Text |Tipe atau kategori pelanggan yang melakukan pemesanan hotel|
|Reserved_room_type| Text | Jenis atau kategori kamar yang telah dipesan oleh pelanggan untuk periode tertentu|
|Required_car_parking_spaces| Long |Jumlah tempat parkir mobil yang diminta atau dibutuhkan oleh pelanggan saat melakukan pemesanan kamar hotel|
|Total_of_special_requests| Long |Jumlah total permintaan khusus atau permintaan tambahan yang diajukan oleh pelanggan saat melakukan pemesanan kamar hotel|
|Is_canceled| Long |0 – Pembatalan Pemesanan, 1 – Tidak Membatalkan Pemesanan|

In [1]:
# Library

import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns
import missingno
from IPython.display import display

In [2]:
#Load Dataset
df = pd.read_csv("data_hotel_booking_demand.csv")
df.head()

,country,market_segment,previous_cancellations,booking_changes,deposit_type,days_in_waiting_list,customer_type,reserved_room_type,required_car_parking_spaces,total_of_special_requests,is_canceled
0,IRL,Offline TA/TO,0,0,No Deposit,0,Transient-Party,A,0,0,0
1,FRA,Online TA,0,0,No Deposit,0,Transient,A,0,2,0
2,PRT,Online TA,0,1,No Deposit,0,Transient,A,0,2,0
3,NLD,Online TA,0,0,No Deposit,0,Transient,A,0,1,1
4,PRT,Online TA,0,2,No Deposit,0,Transient,A,0,2,0

In [3]:
# Count and Datatype for each Column
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83573 entries, 0 to 83572
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   country                      83222 non-null  object
 1   market_segment               83573 non-null  object
 2   previous_cancellations       83573 non-null  int64
 3   booking_changes              83573 non-null  int64
 4   deposit_type                 83573 non-null  object
 5   days_in_waiting_list         83573 non-null  int64
 6   customer_type                83573 non-null  object
 7   reserved_room_type           83573 non-null  object
 8   required_car_parking_spaces  83573 non-null  int64
 9   total_of_special_requests    83573 non-null  int64
 10  is_canceled                  83573 non-null  int64
dtypes: int64(6), object(5)
memory usage: 7.0+ MB

### *Data Cleaning*

In [4]:
listItem = []
for col in df.columns :
    listItem.append([col, df[col].dtype, df[col].isna().sum(), round((df[col].isna().sum()/len(df[col])) * 100,2),
                    df[col].nunique(), list(df[col].drop_duplicates().sample(2).values)]);

dfDesc = pd.DataFrame(columns=['dataFeatures', 'dataType', 'null', 'nullPct', 'unique', 'uniqueSample'],
                     data=listItem)
dfDesc

,dataFeatures,dataType,null,nullPct,unique,uniqueSample
0,country,object,351,0.42,162,"[MWI, AIA]"
1,market_segment,object,0,0.00,8,"[Groups, Direct]"
2,previous_cancellations,int64,0,0.00,15,"[1, 19]"
3,booking_changes,int64,0,0.00,19,"[7, 4]"
4,deposit_type,object,0,0.00,3,"[Refundable, No Deposit]"
5,days_in_waiting_list,int64,0,0.00,115,"[70, 55]"
6,customer_type,object,0,0.00,4,"[Contract, Group]"
7,reserved_room_type,object,0,0.00,10,"[A, G]"
8,required_car_parking_spaces,int64,0,0.00,5,"[8, 3]"
9,total_of_special_requests,int64,0,0.00,6,"[1, 4]"
10,is_canceled,int64,0,0.00,2,"[0, 1]"

## Memvisualisasikan data yang hilang

Setelah kita ....

In [18]:
total = df['is_canceled'].count()

tidak_membatalkan_pesanan = len(df[df['is_canceled'] == 1]) # tidak membatalkan pesanan
membatalkan_pesanan = len(df[df["is_canceled"] == 0])

# max waitiing hour

print(tidak_membatalkan_pesanan, membatalkan_pesanan)

30778 52795

In [ ]:
# Mencari customer typoe yang sering membatalkan pesanan